net:
  hidden_dim: 128
  hidden_deep: 2
  seed: 0

algo:
  gamma: 0.98
  epsilon: 0.1
  batch_size: 64
  mini_size: 500
  lr: 2e-3
  replay_buffer_size: 10000
  target_update_freq: 10


env:
    env_name: "CartPole-v1"
    max_steps: 600
    episodes: 120
